export interface ProductColorVariant {
  color: string;
  colorHex: string;
  urls: string[];
}

export interface Product {
  id: number;
  name: string;
  price: number;
  oldPrice?: number;
  category: string;
  code: string;
  stock: number;
  image: string;
  images?: ProductColorVariant[];
  isNew: boolean;
  isHot: boolean;
  isSale: boolean;
  description: string;
}

export const products: Product[] = [
  {
    id: 57,
    name: "SET PICK - TENIS NEWW 🔥",
    price: 550000,
    category: "Do bo",
    code: "QJ064",
    stock: 18,
    image: "https://i.postimg.cc/8PfHdxHf/p111.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/8PfHdxHf/p111.jpg",
          "https://i.postimg.cc/vZdWrTTJ/p11.jpg",
          "https://i.postimg.cc/Ls5hLFk6/t1.jpg",
          "https://i.postimg.cc/T3XsHnCk/p01.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: false,
    description:
      "✨✨Riêng hàng Nike nhà e a/e bán mãi  thừa biết chất lượng chuẩn Auth ntn không so với hàng trôi nổi trên thị trường.Tỉ mỉ từng đường kim mũi chỉ. ✌🏻",
  },
  {
    id: 56,
    name: "⚡️Bộ PICK - TENIS NEWW 🔥",
    price: 550000,
    category: "Do bo",
    code: "QJ063",
    stock: 14,
    image: "https://i.postimg.cc/VvnJv9qN/t101.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/VvnJv9qN/t101.jpg",
          "https://i.postimg.cc/Ls5hLFk6/t1.jpg",
          "https://i.postimg.cc/02CN4ycm/t11.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: false,
    description:
      "✨✨ Chất vải cotton cao cấp chuẩn hãng siêu thoáng mát, lên dáng cực dễ chịu, thoải mái ✌🏻",
  },
  {
    id: 55,
    name: "⚡️⚡️ Bộ Lacoste !!",
    price: 650000,
    category: "Do bo",
    code: "QJ062",
    stock: 13,
    image: "https://i.postimg.cc/yxd1RmC8/ca1.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/yxd1RmC8/ca1.jpg",
          "https://i.postimg.cc/vT6KCTWC/ca11.jpg",
          "https://i.postimg.cc/zDg5sGDc/ca111.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: false,
    description:
      "✨✨ Chất vải cotton cao cấp chuẩn hãng siêu thoáng mát, lên dáng cực dễ chịu, thoải mái ✌🏻",
  },
  {
    id: 50,
    name: "Siêu phẩm DSQ én 2053",
    price: 450000,
    oldPrice: 520000,
    category: "Do bo",
    code: "QJ057",
    stock: 19,
    image: "https://i.postimg.cc/25kkpTpH/nay1.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/25kkpTpH/nay1.jpg",
          "https://i.postimg.cc/2yZmdKv6/nay11.jpg",
          "https://i.postimg.cc/NG3rhhdz/nay01.jpg",
          "https://i.postimg.cc/KjBjcz92/nay001.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description:
      "Sett Bộ Essential Áo Cotton Quần Chân Cua Hoạ Tiết Cao Su Nổi Dây Hãng Nét Căng ✌🏻",
  },
  {
    id: 49,
    name: "Siêu phẩm DSQ én 2053",
    price: 680000,
    oldPrice: 740000,
    category: "Quan",
    code: "QJ056",
    stock: 11,
    image: "https://i.postimg.cc/bJ6cQR4f/quan11.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/bJ6cQR4f/quan11.jpg",
          "https://i.postimg.cc/2jKNy247/quan1.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description:
      "Siêu phẩm DSQ én 2053 Bản like auth was rách + màu đậm chuẩn 1:1 ✌🏻",
  },
  {
    id: 1,
    name: "Bộ Đồ Thể Thao Vừa Ra Lò NEW",
    price: 600000,
    oldPrice: 740000,
    category: "Do bo",
    code: "QJ054",
    stock: 16,
    image: "https://i.postimg.cc/fbk8GC6S/4.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/fbk8GC6S/4.jpg",
          "https://i.postimg.cc/ZY6wzCD6/04.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: " Full SIZE ae báo đơn e ngay nháa ✌🏻",
  },
  {
    id: 2,
    name: "Ao authu 3 Mẫu New fw2026",
    price: 360000,
    oldPrice: 450000,
    category: "Ao",
    code: "QJ052",
    stock: 16,
    image: "https://i.postimg.cc/GtjtJF3t/2.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/GtjtJF3t/2.jpg",
          "https://i.postimg.cc/L855LgcZ/02.jpg",
          "https://i.postimg.cc/k43g01Bv/002.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description:
      "Thêu giả đan len chéo , bản thêu siêu dày , màu chỉ bóng nổi bật cả áo , viền cho bo gọn siêu nét",
  },
  {
    id: 3,
    name: "Hotttt Polo Dolce",
    price: 290000,
    oldPrice: 350000,
    category: "Ao",
    code: "HD001",
    stock: 18,
    image: "https://i.postimg.cc/4xgpKL0Y/3.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/4xgpKL0Y/3.jpg",
          "https://i.postimg.cc/MKrhqB39/2.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Hotttt Polo Dolce Thêu Kim Tuyến SS26",
  },
  {
    id: 4,
    name: "Hot Polo LV",
    price: 300000,
    category: "Ao",
    code: "QJ002",
    stock: 20,
    image: "https://i.postimg.cc/0y9GrX6Z/4.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/0y9GrX6Z/4.jpg",
          "https://i.postimg.cc/3wm36113/5.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: false,
    description: "Hot Polo LV sang trọng, chất liệu cao cấp",
  },
  {
    id: 5,
    name: "Hottt Sett Bộ Adidas",
    price: 420000,
    category: "Do bo",
    code: "QJ003",
    stock: 23,
    image: "https://i.postimg.cc/GtB777PX/6.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/GtB777PX/6.jpg",
          "https://i.postimg.cc/VkFxbhKy/7.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: false,
    description: "Hottt Sett Bộ Adidas Newww SS26",
  },
  {
    id: 6,
    name: "Set NIKE cực chơi chất",
    price: 425000,
    category: "Do bo",
    code: "QJ004",
    stock: 35,
    image: "https://i.postimg.cc/YCk9HJ4k/8.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/YCk9HJ4k/8.jpg",
          "https://i.postimg.cc/mDcZj4n5/9.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Áo ctong in thẩm thấu - quần gió dù 2 lớp",
  },
  {
    id: 7,
    name: "Bộ PUMA đội tuyển Manchester City",
    price: 420000,
    category: "Do bo",
    code: "QJ005",
    stock: 17,
    image: "https://i.postimg.cc/J0mgncjx/10.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/J0mgncjx/10.jpg",
          "https://i.postimg.cc/ZqdDxDc0/11.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: false,
    description: "Hottt Sett Bộ PUMA Man City Newww SS26",
  },
  {
    id: 8,
    name: "Polo Dior Đính Bọ",
    price: 290000,
    oldPrice: 370000,
    category: "Ao",
    code: "HN2006",
    stock: 37,
    image: "https://i.postimg.cc/fy16stM7/12.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/fy16stM7/12.jpg",
          "https://i.postimg.cc/PfBXTN3v/13.jpg",
          "https://i.postimg.cc/wjkgX264/14.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Polo Dior Đính Bọ cực tinh tế SS26",
  },
  {
    id: 9,
    name: "Polo Gucci Hoạ Tiết Thêu Túi",
    price: 290000,
    oldPrice: 400000,
    category: "Ao",
    code: "HN2007",
    stock: 37,
    image: "https://i.postimg.cc/zXcnJwZN/71.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/zXcnJwZN/71.jpg",
          "https://i.postimg.cc/90f720Jk/72jpg.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Hotttt Polo Gucci Hoạ Tiết Thêu Túi SS26",
  },
  {
    id: 10,
    name: "TÚI CHÉO QUẢNG CHÂU NEW",
    price: 500000,
    oldPrice: 750000,
    category: "Tui",
    code: "HN2000",
    stock: 39,
    image: "https://i.postimg.cc/437GDg62/tui1.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: ["https://i.postimg.cc/437GDg62/tui1.jpg"],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Túi chéo Quảng Châu mẫu mới nhất",
  },
  {
    id: 11,
    name: "Dép Siêu Cấp Lv",
    price: 290000,
    oldPrice: 440000,
    category: "Dep",
    code: "HN2009",
    stock: 37,
    image: "https://i.postimg.cc/Zq3gPKFY/dep1.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: ["https://i.postimg.cc/Zq3gPKFY/dep1.jpg"],
      },
    ],
    isNew: true,
    isHot: false,
    isSale: true,
    description: "Fom Chuẩn Like Auth, Quai Cao Su In Hoạ Tiết Nổi Bật !",
  },
  {
    id: 12,
    name: "Hotttt Polo Louis Vuitton",
    price: 320000,
    category: "Ao",
    code: "QJ012",
    stock: 27,
    image: "https://i.postimg.cc/L8ZR7SBj/101.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/L8ZR7SBj/101.jpg",
          "https://i.postimg.cc/q7srJGF3/102.jpg",
          "https://i.postimg.cc/QCtZqZdQ/103.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: false,
    isSale: false,
    description: "Hotttt Polo Louis Vuitton Thêu Thuyền Nét Keng SS26",
  },
  {
    id: 13,
    name: "TÚI CHÉO QUẢNG CHÂU NEW MẪU 2",
    price: 450000,
    category: "Tui",
    code: "QJ013",
    stock: 16,
    image: "https://i.postimg.cc/pVhHyx44/tui2.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: ["https://i.postimg.cc/pVhHyx44/tui2.jpg"],
      },
    ],
    isNew: true,
    isHot: false,
    isSale: false,
    description: "FULL BILL THẺ GIẤY TỜ ĐẦY ĐỦ💥",
  },
  {
    id: 14,
    name: "TÚI CHÉO QUẢNG CHÂU NEW",
    price: 430000,
    category: "Tui",
    code: "QJ014",
    stock: 21,
    image: "https://i.postimg.cc/TPBXJ4Dv/tui3.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: ["https://i.postimg.cc/TPBXJ4Dv/tui3.jpg"],
      },
    ],
    isNew: true,
    isHot: false,
    isSale: false,
    description: "FULL BILL THẺ GIẤY TỜ ĐẦY ĐỦ💥",
  },
  {
    id: 15,
    name: "Dép DG New ",
    price: 230000,
    category: "Dep",
    code: "QJ015",
    stock: 26,
    image: "https://i.postimg.cc/NfZ7Y8m5/dep2.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: ["https://i.postimg.cc/NfZ7Y8m5/dep2.jpg"],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: false,
    description: "Đế Cao Su 2 Lớp Êm Chân!!",
  },
  {
    id: 16,
    name: " Set NIKE ",
    price: 440000,
    category: "Do bo",
    code: "QJ016",
    stock: 11,
    image: "https://i.postimg.cc/T10YdvkX/141.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/T10YdvkX/141.jpg",
          "https://i.postimg.cc/qqJ4ZZp3/142.jpg",
          "https://i.postimg.cc/Dz1hfK0k/143.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: false,
    isSale: false,
    description:
      "hang co giãn mặc cực mát luôn fom dáng cứ phải gọi là hết nước chấm. Ông a hàng xóm nhờ bán hộ ",
  },
  {
    id: 17,
    name: "Hottt Sett Bộ  Adidas ",
    price: 425000,
    oldPrice: 540000,
    category: "Do bo",
    code: "QJ019",
    stock: 13,
    image: "https://i.postimg.cc/9fgkj8PS/151.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/9fgkj8PS/151.jpg",
          "https://i.postimg.cc/rwQnSnHW/152.jpg",
          "https://i.postimg.cc/qqsQgjnq/153.jpg",
          "https://i.postimg.cc/NftpZvqX/154.jpg",
          "https://i.postimg.cc/SsDxqp1k/155.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: false,
    description: "Hoa tiết in dập nổi 2 lớp",
  },
  {
    id: 18,
    name: "3 Mẫu Hot Dép LV New ",
    price: 290000,
    category: "Dep",
    code: "QJ018",
    stock: 26,
    image: "https://i.postimg.cc/jjRTjF7q/dep3.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/jjRTjF7q/dep3.jpg",
          "https://i.postimg.cc/Y0BKJDky/dep4.jpg",
          "https://i.postimg.cc/x1pr01n7/dep5.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: false,
    description: "Đế Cao Su 2 Lớp Êm Chân, Chuẩn hàng AUth!!",
  },
  {
    id: 19,
    name: "2 Mẫu Dép LV New ",
    price: 270000,
    category: "Dep",
    code: "QJ020",
    stock: 9,
    image: "https://i.postimg.cc/MH95yXP2/dep7.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/MH95yXP2/dep7.jpg",
          "https://i.postimg.cc/fW8fqtKX/dep6.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Đế Cao Su 2 Lớp Êm Chân, Chuẩn hàng AUth!!",
  },
  {
    id: 20,
    name: "Túi Chéo Quảng Chau NEW",
    price: 550000,
    category: "Tui",
    code: "QJ021",
    stock: 16,
    image: "https://i.postimg.cc/zvpNKSZk/tui4.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: ["https://i.postimg.cc/zvpNKSZk/tui4.jpg"],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "HÀNG FULL 2 BOX 🔥🔥,FULL BILL THẺ GIẤY TỜ ĐẦY ĐỦ💥",
  },
  {
    id: 21,
    name: "Dép Tông Lv New",
    price: 250000,
    category: "Dep",
    code: "QJ025",
    stock: 37,
    image: "https://i.postimg.cc/ZYwXPqvX/dep8.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/ZYwXPqvX/dep8.jpg",
          "https://i.postimg.cc/NGCP9PZ3/dep9.jpg",
          "https://i.postimg.cc/gJTqJ1r4/dep10.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Toàn Các Màu Hot New Nhất 2026🥰",
  },
  {
    id: 22,
    name: " 3 Mẫu Dép DG New",
    price: 230000,
    oldPrice: 340000,
    category: "Dep",
    code: "QJ026",
    stock: 29,
    image: "https://i.postimg.cc/qMTVMFnz/ch.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/qMTVMFnz/ch.jpg",
          "https://i.postimg.cc/0N3hgXP5/dephot.jpg",
          "https://i.postimg.cc/Yq3V2Ctc/dephot1.jpg",
          "https://i.postimg.cc/hPyr3zSX/dephay1.jpg",
          "https://i.postimg.cc/ZR8HfwqD/dephay.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Toàn Các Màu Hot New Nhất 2026🥰",
  },
  {
    id: 23,
    name: "⚜️ Short Gió DSQ ",
    price: 280000,
    oldPrice: 320000,
    category: "Quan",
    code: "QJ031",
    stock: 21,
    image: "https://i.postimg.cc/fTJ2sjqf/quan3.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/fTJ2sjqf/quan3.jpg",
          "https://i.postimg.cc/9MLb5rG0/quan4.jpg",
          "https://i.postimg.cc/J4fqLwBb/quan5.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: false,
    isSale: false,
    description: "⚜️ Short Gió DSQ Icon Hoạ Tiết Hot Về Hai Màu !",
  },
  {
    id: 24,
    name: "Shorc Gió DG ",
    price: 299000,
    oldPrice: 370000,
    category: "Quan",
    code: "QJ030",
    stock: 16,
    image: "https://i.postimg.cc/X7f84Hcb/quan6.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/X7f84Hcb/quan6.jpg",
          "https://i.postimg.cc/nrvvVrm0/quan66.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Chất gió dày dặn . 2 lớp AE nha !",
  },
  {
    id: 25,
    name: "Shorc Gió DG ",
    price: 280000,
    oldPrice: 370000,
    category: "Quan",
    code: "QJ029",
    stock: 34,
    image: "https://i.postimg.cc/bvDSNdcg/quanngan1.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/bvDSNdcg/quanngan1.jpg",
          "https://i.postimg.cc/52j6nj0c/quanngan2.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Chất gió dày dặn . 2 lớp AE nha !",
  },
  {
    id: 26,
    name: "Shorc Gió DG ",
    price: 290000,
    oldPrice: 380000,
    category: "Quan",
    code: "QJ034",
    stock: 25,
    image: "https://i.postimg.cc/9F0mjKj8/quan7.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/9F0mjKj8/quan7.jpg",
          "https://i.postimg.cc/85TGXnHc/quan77.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Chất gió dày dặn . 2 lớp AE nha !",
  },
  {
    id: 27,
    name: "Shorc Gió DG ",
    price: 290000,
    oldPrice: 350000,
    category: "Quan",
    code: "QJ035",
    stock: 42,
    image: "https://i.postimg.cc/5NKwxhQ6/quan8.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/5NKwxhQ6/quan8.jpg",
          "https://i.postimg.cc/D0yXh62W/quan88.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: false,
    isSale: false,
    description: "Chất gió dày dặn . 2 lớp AE nha !",
  },
  {
    id: 28,
    name: "Hottt Sett Bộ  Adidas ",
    price: 420000,
    oldPrice: 550000,
    category: "Do bo",
    code: "QJ036",
    stock: 17,
    image: "https://i.postimg.cc/7h3wBrvg/9.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/7h3wBrvg/9.jpg",
          "https://i.postimg.cc/FKYvML54/12.jpg",
          "https://i.postimg.cc/hv1RL8xT/121.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Hottt Sett Bộ  Adidas   Newww SS26 !",
  },
  {
    id: 29,
    name: "Hottt Sett Bộ Adidas NEW ",
    price: 410000,
    oldPrice: 500000,
    category: "Do bo",
    code: "QJ036",
    stock: 14,
    image: "https://i.postimg.cc/PJhB5LcZ/10.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/PJhB5LcZ/10.jpg",
          "https://i.postimg.cc/X7sTnYg6/11.jpg",
          "https://i.postimg.cc/VvYVcxrt/1111.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Hottt Sett Bộ  Adidas   Newww SS26 !",
  },
  {
    id: 30,
    name: "Hottt Sett Bộ Adidas NEW ",
    price: 430000,
    oldPrice: 550000,
    category: "Do bo",
    code: "QJ037",
    stock: 23,
    image: "https://i.postimg.cc/0NkMDZwb/13.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/0NkMDZwb/13.jpg",
          "https://i.postimg.cc/Qx76Vg1L/1313.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Hottt Sett Bộ  Adidas   Newww SS26 !",
  },
  {
    id: 31,
    name: "Sét polo quần gió ",
    price: 420000,
    oldPrice: 500000,
    category: "Do bo",
    code: "QJ038",
    stock: 23,
    image: "https://i.postimg.cc/wTBqpvN8/14.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/wTBqpvN8/14.jpg",
          "https://i.postimg.cc/QtbDLGxN/141.jpg",
          "https://i.postimg.cc/s2CCvDvm/1414.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: false,
    isSale: false,
    description: "Sét polo quần gió trông chơi luôn AE !",
  },
  {
    id: 32,
    name: "Hottt Sett Bộ  lacote",
    price: 410000,
    oldPrice: 480000,
    category: "Do bo",
    code: "QJ039",
    stock: 27,
    image: "https://i.postimg.cc/RCWms8xB/15.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/RCWms8xB/15.jpg",
          "https://i.postimg.cc/g0cFvtHV/151.jpg",
          "https://i.postimg.cc/MT4CJ6Jk/16.jpg",
          "https://i.postimg.cc/gk3f1bMB/161.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: false,
    isSale: true,
    description:
      "Hottt Sett Bộ  lacote    Newww SS26, Hoa tiết in cao su bóng ",
  },
  {
    id: 33,
    name: "Bộ PUMA đội tuyển Manchester City",
    price: 430000,
    oldPrice: 550000,
    category: "Do bo",
    code: "QJ040",
    stock: 27,
    image: "https://i.postimg.cc/gJvVms14/01.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/gJvVms14/01.jpg",
          "https://i.postimg.cc/ZnH6yRbg/010.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Newwww ae ơi Bộ PUMA đội tuyển Manchester City ",
  },
  {
    id: 34,
    name: "Hottt Sett Bộ  Nike  2 Màu Newww SS26",
    price: 410000,
    oldPrice: 499000,
    category: "Do bo",
    code: "QJ042",
    stock: 32,
    image: "https://i.postimg.cc/kg4LGRM7/02.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/kg4LGRM7/02.jpg",
          "https://i.postimg.cc/sf4LJ4vs/020.jpg",
          "https://i.postimg.cc/wvcw09xT/03.jpg",
          "https://i.postimg.cc/v8hPn8NT/030.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: false,
    isSale: true,
    description: "Hoa tiết in cao thành . In full không phải in lưới  ",
  },
  {
    id: 35,
    name: " Set NI.KE 2 MÀu cực chơi chất quần nỉ",
    price: 450000,
    oldPrice: 570000,
    category: "Do bo",
    code: "QJ043",
    stock: 23,
    image: "https://i.postimg.cc/N0tJTyBv/04.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/N0tJTyBv/04.jpg",
          "https://i.postimg.cc/J0SKh0P9/040.jpg",
          "https://i.postimg.cc/rwXQXddW/05.jpg",
          "https://i.postimg.cc/sXXJ97Lk/050.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Hoa tiết in cao thành . In full không phải in lưới  ",
  },
  {
    id: 36,
    name: " Polo Christian Dior",
    price: 300000,
    oldPrice: 410000,
    category: "Ao",
    code: "QJ044",
    stock: 45,
    image: "https://i.postimg.cc/130xL1zs/1.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/130xL1zs/1.jpg",
          "https://i.postimg.cc/tTTLZ1N1/111.jpg",
          "https://i.postimg.cc/DftwhF78/01.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Hotttt Polo Christian Dior Logo Thêu Con Ngựa SS26  ",
  },
  {
    id: 37,
    name: " Polo Christian Dior",
    price: 320000,
    oldPrice: 450000,
    category: "Ao",
    code: "QJ045",
    stock: 22,
    image: "https://i.postimg.cc/ZnL7w4c8/2.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/ZnL7w4c8/2.jpg",
          "https://i.postimg.cc/8zYyKyRJ/02.jpg",
          "https://i.postimg.cc/vBr3mbpf/22.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "HHotttt Polo Christian Dior Logo Thêu Nét Keng SS26  ",
  },
  {
    id: 38,
    name: "Polo Celine Paris ",
    price: 340000,
    oldPrice: 410000,
    category: "Ao",
    code: "QJ046",
    stock: 12,
    image: "https://i.postimg.cc/7Lv3Jj1f/03.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/7Lv3Jj1f/03.jpg",
          "https://i.postimg.cc/WbCrxxHC/3.jpg",
          "https://i.postimg.cc/D0mJMcdn/33.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Hotttt Polo Celine Paris Thêu Xù Net Keng SS26  ",
  },
  {
    id: 39,
    name: "TÚI CHÉO QUẢNG CHÂU NEW",
    price: 540000,
    oldPrice: 610000,
    category: "Tui",
    code: "QJ047",
    stock: 12,
    image: "https://i.postimg.cc/3NxBK6mg/tui1.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: ["https://i.postimg.cc/3NxBK6mg/tui1.jpg"],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "HÀNG FULL 2 BOX 🔥🔥. FULL BILL THẺ GIẤY TỜ ĐẦY ĐỦ💥",
  },
  {
    id: 40,
    name: "TÚI CHÉO Chất QUẢNG CHÂU NEW",
    price: 400000,
    oldPrice: 550000,
    category: "Tui",
    code: "QJ048",
    stock: 11,
    image: "https://i.postimg.cc/vBBhykWg/tui2.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/vBBhykWg/tui2.jpg",
          "https://i.postimg.cc/d1Lf6LSF/tui22.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: false,
    isSale: false,
    description: "HÀNG FULL 2 BOX 🔥🔥. FULL BILL THẺ GIẤY TỜ ĐẦY ĐỦ💥",
  },
  {
    id: 41,
    name: "TÚI CHÉO LV QUẢNG CHÂU NEW",
    price: 450000,
    oldPrice: 570000,
    category: "Tui",
    code: "QJ049",
    stock: 17,
    image: "https://i.postimg.cc/gJZDrRTb/tui3.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: ["https://i.postimg.cc/gJZDrRTb/tui3.jpg"],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "HÀNG FULL 2 BOX 🔥🔥. FULL BILL THẺ GIẤY TỜ ĐẦY ĐỦ💥",
  },
  {
    id: 42,
    name: "TÚI CHÉO LV QUẢNG CHÂU NEW",
    price: 470000,
    oldPrice: 570000,
    category: "Tui",
    code: "QJ049",
    stock: 17,
    image: "https://i.postimg.cc/3R5GSqtN/tui5.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: ["https://i.postimg.cc/3R5GSqtN/tui5.jpg"],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "HÀNG FULL 2 BOX 🔥🔥. FULL BILL THẺ GIẤY TỜ ĐẦY ĐỦ💥",
  },
  {
    id: 43,
    name: "Jean D2 khoá lệch Xanh",
    price: 680000,
    oldPrice: 750000,
    category: "Quan",
    code: "QJ050",
    stock: 45,
    image: "https://i.postimg.cc/0QHBB3t6/09.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/0QHBB3t6/09.jpg",
          "https://i.postimg.cc/SK1BBJRL/909.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Jean D2 khoá lệch điểm nhấn slogan was rách siêu hịn onweb",
  },
  {
    id: 44,
    name: "Jean D2 khoá lệch Đen",
    price: 680000,
    oldPrice: 780000,
    category: "Quan",
    code: "QJ050",
    stock: 22,
    image: "https://i.postimg.cc/Gh3jyzqY/4.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/Gh3jyzqY/4.jpg",
          "https://i.postimg.cc/Wz5g8LXZ/40.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Jean D2 khoá lệch điểm nhấn slogan was rách siêu hịn onweb",
  },
  {
    id: 45,
    name: "T-Shirt 𝐊𝐄𝐍𝐙𝐎",
    price: 450000,
    oldPrice: 520000,
    category: "Ao",
    code: "QJ051",
    stock: 22,
    image: "https://i.postimg.cc/pdMhDLRc/5.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/pdMhDLRc/5.jpg",
          "https://i.postimg.cc/Jh7yTdHR/51.jpg",
          "https://i.postimg.cc/m2xPxrFs/52.jpg",
          "https://i.postimg.cc/7LL61GjK/53.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Chất vải, form dáng thì cứ phải là chuẩn auth xịn đét",
  },
  {
    id: 46,
    name: "Tee 1V  New fw2026",
    price: 465000,
    oldPrice: 550000,
    category: "Ao",
    code: "QJ051",
    stock: 16,
    image: "https://i.postimg.cc/s2KWsRCh/1.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/s2KWsRCh/1.jpg",
          "https://i.postimg.cc/RC2XjwRq/11.jpg",
          "https://i.postimg.cc/kgvs6zdC/011.jpg",
          "https://i.postimg.cc/yN6PFjVQ/001.jpg",
          "https://i.postimg.cc/vTnLQSzB/111.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description:
      "Thêu giả đan len chéo , bản thêu siêu dày , màu chỉ bóng nổi bật cả áo , viền cho bo gọn siêu nét",
  },
  {
    id: 47,
    name: "Mã LV onlweb",
    price: 380000,
    oldPrice: 440000,
    category: "Ao",
    code: "QJ053",
    stock: 16,
    image: "https://i.postimg.cc/YSN5Sbdf/3.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/YSN5Sbdf/3.jpg",
          "https://i.postimg.cc/sfHt1B4q/03.jpg",
          "https://i.postimg.cc/gkfQqf51/303.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: " Full 4 màu basic ae báo đơn e ngay nháa ✌🏻",
  },
  {
    id: 48,
    name: "Phông LV đỉnh nhất thị trường",
    price: 420000,
    oldPrice: 540000,
    category: "Ao",
    code: "QJ055",
    stock: 16,
    image: "https://i.postimg.cc/02FjGy9x/5.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/02FjGy9x/5.jpg",
          "https://i.postimg.cc/MHXZRhL3/05.jpg",
          "https://i.postimg.cc/HWPkHkcM/005.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description:
      " Màu đen trắng đỏ đô thì quá ưng rồi, logo thêu nét căng, ae păm luôn cho nóng ✌🏻",
  },
  {
    id: 51,
    name: "Thắt Lưng Hàng NeW vừa cập bến !!",
    price: 250000,
    oldPrice: 320000,
    category: "That lung",
    code: "QJ058",
    stock: 14,
    image: "https://i.postimg.cc/gcqgZcXh/t1.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: ["https://i.postimg.cc/gcqgZcXh/t1.jpg"],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Thắt lưng Hãng Nét Căng ✌🏻",
  },
  {
    id: 52,
    name: "Thắt Lưng Hàng NeW vừa cập bến !!",
    price: 2490000,
    oldPrice: 320000,
    category: "That lung",
    code: "QJ059",
    stock: 14,
    image: "https://i.postimg.cc/G2PxGz2H/t01.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: ["https://i.postimg.cc/G2PxGz2H/t01.jpg"],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Thắt lưng Hãng Nét Căng ✌🏻",
  },
  {
    id: 53,
    name: "Thắt Lưng Hàng NeW vừa cập bến !!",
    price: 2450000,
    oldPrice: 330000,
    category: "That lung",
    code: "QJ060",
    stock: 19,
    image: "https://i.postimg.cc/k4CxJ8cq/t11.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: ["https://i.postimg.cc/k4CxJ8cq/t11.jpg"],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Thắt lưng Hãng Nét Căng ✌🏻",
  },
  {
    id: 54,
    name: "Thắt Lưng Hàng NeW vừa cập bến !!",
    price: 2450000,
    oldPrice: 330000,
    category: "That lung",
    code: "QJ061",
    stock: 19,
    image: "https://i.postimg.cc/rmqrXTV8/tt1.jpg",
    images: [
      {
        color: "Tat ca",
        colorHex: "#000000",
        urls: [
          "https://i.postimg.cc/rmqrXTV8/tt1.jpg",
          "https://i.postimg.cc/TP6ygxWh/t101.jpg",
          "https://i.postimg.cc/D0H0Z3T7/ttt1.jpg",
        ],
      },
    ],
    isNew: true,
    isHot: true,
    isSale: true,
    description: "Thắt lưng Hãng Nét Căng ✌🏻",
  },
];

export const categories = [
  { id: "all", name: "Tat Ca", icon: "🔥" },
  { id: "Ao", name: "Ao", icon: "👕" },
  { id: "Quan", name: "Quan", icon: "👖" },
  { id: "Do bo", name: "Do Bo", icon: "👔" },
  { id: "Giay", name: "Giay", icon: "👟" },
  { id: "Dep", name: "Dep", icon: "🩴" },
  { id: "That lung", name: "That Lung", icon: "🔗" },
  { id: "Tui", name: "Tui", icon: "👜" },
  { id: "Mu", name: "Mu", icon: "🧢" },
  { id: "Dong ho", name: "Dong Ho", icon: "⌚" },
];

export const ZALO_NUMBER = "0862536206";
export const FACEBOOK_ID = "hoang.ninh.79677471";

export const vietnameseNames = [
  "Minh Anh",
  "Hoang Long",
  "Thu Huong",
  "Duc Minh",
  "Ngoc Anh",
  "Quang Huy",
  "Mai Linh",
  "Tuan Kiet",
  "Phuong Thao",
  "Duy Khang",
  "Thanh Hang",
  "Bao Ngoc",
  "Hoai Nam",
  "Kim Chi",
  "Van Anh",
  "Truong Giang",
  "Thuy Tien",
  "Duc Anh",
  "My Linh",
  "Quoc Viet",
  "Phan Huy",
  "Huy Huong",
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("vi-VN").format(price) + "đ";
}

export function getZaloLink(productCode: string, productName: string): string {
  const message = encodeURIComponent(
    `Toi muon mua san pham [${productCode}] - ${productName}`,
  );
  return `https://zalo.me/${ZALO_NUMBER}?text=${message}`;
}

export function getFacebookLink(
  productCode: string,
  productName: string,
): string {
  const message = encodeURIComponent(
    `Toi muon mua san pham [${productCode}] - ${productName}`,
  );
  return `https://m.me/${FACEBOOK_ID}?text=${message}`;
}
